# Generated by Django 4.2.30 on 2026-05-19 08:52

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('listing_type', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent'), ('lease', 'For Lease')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('sold', 'Sold'), ('rented', 'Rented'), ('inactive', 'Inactive')], default='draft', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('negotiable', models.BooleanField(default=False)),
                ('land_area', models.DecimalField(decimal_places=2, help_text='Land area value', max_digits=12)),
                ('land_area_unit', models.CharField(default='sqft', help_text='sqft, sqm, kattha, ropani, bigha etc.', max_length=30)),
                ('built_up_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('floors', models.PositiveIntegerField(default=0)),
                ('address', models.CharField(max_length=255)),
                ('ward_no', models.CharField(blank=True, max_length=20, null=True)),
                ('municipality', models.CharField(blank=True, max_length=150, null=True)),
                ('district', models.CharField(blank=True, max_length=150, null=True)),
                ('province', models.CharField(blank=True, max_length=150, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Property point location', srid=4326)),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, help_text='Optional property parcel boundary', null=True, srid=4326)),
                ('road_access_width', models.DecimalField(blank=True, decimal_places=2, help_text='Road width near property', max_digits=6, null=True)),
                ('road_access_unit', models.CharField(default='meter', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent'), ('lease', 'Lease')], max_length=20)),
                ('transaction_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transaction_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('buyer_or_renter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_transactions', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='properties.property')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='PropertyInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='properties.property')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('lalpurja', 'Lalpurja'), ('map', 'Cadastral Map'), ('blueprint', 'Blueprint'), ('tax_receipt', 'Tax Receipt'), ('ownership', 'Ownership Document'), ('other', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to='properties/documents/')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.property')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_property_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='properties', to='properties.propertyfeature'),
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.propertytype'),
        ),
        migrations.AddField(
            model_name='property',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FavoriteProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status'], name='properties__status_6427a0_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['listing_type'], name='properties__listing_890379_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price'], name='properties__price_32e7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['created_at'], name='properties__created_72ecc3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favoriteproperty',
            unique_together={('user', 'property')},
        ),
    ]
