# Generated by Django 4.2.30 on 2026-05-19 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteproperty',
            options={},
        ),
        migrations.AlterModelOptions(
            name='propertyfeature',
            options={'ordering': ['property_type', 'ordering', 'name']},
        ),
        migrations.AlterModelOptions(
            name='propertyimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='propertyinquiry',
            options={},
        ),
        migrations.AlterModelOptions(
            name='propertytransaction',
            options={},
        ),
        migrations.RemoveField(
            model_name='property',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='built_up_area',
        ),
        migrations.RemoveField(
            model_name='property',
            name='features',
        ),
        migrations.RemoveField(
            model_name='property',
            name='floors',
        ),
        migrations.RemoveField(
            model_name='propertytype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='propertytype',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='propertyfeature',
            name='choices',
            field=models.JSONField(blank=True, help_text='Example: ["North", "South", "East", "West"]', null=True),
        ),
        migrations.AddField(
            model_name='propertyfeature',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('choice', 'Choice')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyfeature',
            name='is_filterable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='propertyfeature',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertyfeature',
            name='ordering',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='propertyfeature',
            name='property_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='properties.propertytype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyfeature',
            name='unit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='favoriteproperty',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
        migrations.AlterField(
            model_name='favoriteproperty',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='land_area',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='property',
            name='land_area_unit',
            field=models.CharField(default='sqft', max_length=30),
        ),
        migrations.AlterField(
            model_name='property',
            name='road_access_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='propertydocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertyfeature',
            name='code',
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='propertyfeature',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propertyinquiry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertytransaction',
            name='buyer_or_renter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='propertyfeature',
            unique_together={('property_type', 'code')},
        ),
        migrations.RemoveField(
            model_name='propertyfeature',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='propertyfeature',
            name='is_active',
        ),
        migrations.CreateModel(
            name='PropertyFeatureValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.IntegerField(blank=True, null=True)),
                ('value_decimal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='properties.propertyfeature')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_values', to='properties.property')),
            ],
            options={
                'unique_together': {('property', 'feature')},
            },
        ),
    ]
