# Generated by Django 4.2.30 on 2026-05-19 11:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_addressgeojsonupload'),
        ('properties', '0002_alter_favoriteproperty_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_no', models.CharField(max_length=100)),
                ('sheet_no', models.CharField(blank=True, max_length=100, null=True)),
                ('map_no', models.CharField(blank=True, max_length=100, null=True)),
                ('land_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('land_area_unit', models.CharField(default='sqft', max_length=30)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('is_active', models.BooleanField(default=True)),
                ('address_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to='address.addressnode')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='properties.property')),
            ],
            options={
                'unique_together': {('property', 'parcel_no')},
            },
        ),
    ]
