# Generated by Django 4.2.30 on 2026-05-20 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_agency_agencyemployee'),
        ('properties', '0003_parcel'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='accounts.agency'),
        ),
    ]
