# Generated by Django 4.2.30 on 2026-05-20 05:49

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpatialLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.SlugField(blank=True, max_length=180, unique=True)),
                ('layer_type', models.CharField(choices=[('vector', 'Vector'), ('raster', 'Raster')], max_length=20)),
                ('geometry_type', models.CharField(choices=[('point', 'Point'), ('linestring', 'LineString'), ('polygon', 'Polygon'), ('multipolygon', 'MultiPolygon'), ('none', 'None / Raster')], default='none', max_length=30)),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('geojson', 'GeoJSON'), ('shapefile', 'Shapefile'), ('geotiff', 'GeoTIFF'), ('wms', 'WMS'), ('wfs', 'WFS'), ('geoserver', 'GeoServer'), ('external_api', 'External API')], default='manual', max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('geoserver_workspace', models.CharField(blank=True, max_length=100, null=True)),
                ('geoserver_layer_name', models.CharField(blank=True, max_length=150, null=True)),
                ('wms_url', models.URLField(blank=True, null=True)),
                ('wfs_url', models.URLField(blank=True, null=True)),
                ('style_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_queryable', models.BooleanField(default=True)),
                ('is_editable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layers', to='gis_layers.layercategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_spatial_layers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SpatialFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('line', django.contrib.gis.db.models.fields.LineStringField(blank=True, geography=True, null=True, srid=4326)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326)),
                ('multipolygon', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326)),
                ('properties', models.JSONField(blank=True, help_text='Stores dynamic attribute values as JSON', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_spatial_features', to=settings.AUTH_USER_MODEL)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='gis_layers.spatiallayer')),
            ],
            options={
                'ordering': ['layer', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RasterLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raster_file', models.FileField(blank=True, null=True, upload_to='gis_layers/rasters/')),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('pixel_size', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('no_data_value', models.CharField(blank=True, max_length=50, null=True)),
                ('srid', models.PositiveIntegerField(default=4326)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('layer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raster_detail', to='gis_layers.spatiallayer')),
            ],
        ),
        migrations.CreateModel(
            name='LayerUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_type', models.CharField(choices=[('geojson', 'GeoJSON'), ('shapefile', 'Shapefile'), ('geotiff', 'GeoTIFF'), ('csv', 'CSV')], max_length=30)),
                ('file', models.FileField(upload_to='gis_layers/uploads/')),
                ('name_field', models.CharField(blank=True, help_text='Feature name field from uploaded data', max_length=100, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('processing_message', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='gis_layers.spatiallayer')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LayerAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(blank=True, max_length=120)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'DateTime'), ('choice', 'Choice')], max_length=30)),
                ('choices', models.JSONField(blank=True, help_text='For choice field. Example: ["High", "Medium", "Low"]', null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('is_filterable', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='gis_layers.spatiallayer')),
            ],
            options={
                'ordering': ['layer', 'ordering', 'name'],
                'unique_together': {('layer', 'code')},
            },
        ),
        migrations.CreateModel(
            name='FeatureAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_integer', models.IntegerField(blank=True, null=True)),
                ('value_decimal', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_datetime', models.DateTimeField(blank=True, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='gis_layers.layerattribute')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='gis_layers.spatialfeature')),
            ],
            options={
                'unique_together': {('feature', 'attribute')},
            },
        ),
    ]
