# Generated by Django 4.2.30 on 2026-05-19 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_addresslevel_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressGeoJSONUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='addresses/geojson/')),
                ('name_property', models.CharField(default='name', help_text='GeoJSON property key containing address name. Example: name, DISTRICT, province', max_length=100)),
                ('code_property', models.CharField(blank=True, help_text='Optional GeoJSON property key containing code', max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geojson_uploads', to='address.addresslevel')),
                ('parent', models.ForeignKey(blank=True, help_text='Select parent node. Example: Nepal for Province upload, Province for District upload.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geojson_child_uploads', to='address.addressnode')),
            ],
        ),
    ]
